name: Build & deploy to development

on:
  push:
    branches:
      - develop
      - CP-*
      - nexus-*
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Linux, Windows, macOS]
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3
      - name: Setup Env for Windows
        env:
          PHRASE_API_KEY: ${{ secrets.PHRASE_API_KEY }}
          PHRASE_API_URL: ${{ secrets.PHRASE_API_URL }}
          PHRASE_API_KEY_DEV: ${{ secrets.PHRASE_API_KEY_DEV }}
          MUDITA_CENTER_SERVER_URL: ${{ secrets.MUDITA_CENTER_SERVER_URL }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
          RELEASES_REPOSITORY_NAME: ${{ secrets.RELEASES_REPOSITORY_NAME }}
          PRERELEASES_ENABLED: ${{ secrets.PRERELEASES_ENABLED }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MC_GITHUB_ACCESS_TOKEN }}
          LOGIN_MICROSOFT_ONLINE_CLIENT_ID: ${{ secrets.LOGIN_MICROSOFT_ONLINE_CLIENT_ID }}
          FONTS_DIRECTORY_URL: ${{ secrets.FONTS_DIRECTORY_URL }}
          FRESHDESK_API_URL: ${{ secrets.FRESHDESK_API_URL }}
          FRESHDESK_API_TOKEN: ${{ secrets.FRESHDESK_API_TOKEN }}
          ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
          ANALYTICS_API_URL: ${{ secrets.ANALYTICS_API_URL }}
          ANALYTICS_API_SITE_ID: ${{ secrets.ANALYTICS_API_SITE_ID }}
          FEATURE_TOGGLE_ENVIRONMENT: ${{ secrets.FEATURE_TOGGLE_ENVIRONMENT }}
          STATIC_CONFIGURATION_FILE_PATH: ${{ secrets.STATIC_CONFIGURATION_FILE_PATH }}
          DEV_REDUX_LOGGER_ENABLED: ${{ secrets.DEV_REDUX_LOGGER_ENABLED }}
          DEV_DEVICE_LOGGER_ENABLED: ${{ secrets.DEV_DEVICE_LOGGER_ENABLED }}
          FEATURE_TOGGLE_RELEASE_ENVIRONMENT: ${{ secrets.FEATURE_TOGGLE_RELEASE_ENVIRONMENT }}
          MUDITA_CENTER_PRERELEASE_ENABLED: ${{ secrets.MUDITA_CENTER_PRERELEASE_ENABLED }}
        shell: cmd
        if: matrix.os == 'Windows'
        run: |
          SET > .env
          jq -r -j .version packages/app/package.json > packages/app/version
        if: matrix.os != 'Windows'
        run:
          printenv > .env
      - name: Setup depedencies
        run: npm run setup
      - name: Copy electron-builder environment file
        if: matrix.os == 'Windows'
        run: |
          copy C:\actions-runner\envs\electron-builder.env packages/app/electron-builder.env
        if: matrix.os != 'Windows'
        run: |
          cp ~/actions-runner/envs/electron-builder.env packages/app/electron-builder.env
      - name: Build App
        if: matrix.os == 'Windows'
        run: |
          $env:NODE_OPTIONS="--max-old-space-size=4096"
          cd packages/app/
          npm run dist:prod:all
        if: matrix.os != 'Windows'
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          cd packages/app/
          npm run dist:prod:all
          exit 1
      - name: Push artifacts to nexus registry
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          $APP_VERSION = Get-Content -Path "packages/app/version"
          $SOURCE_BRANCH = "${{ github.ref_name }}"
          if ($SOURCE_BRANCH -eq "develop" -or $SOURCE_BRANCH -eq "nexus-runner") {
              $ENVIRONMENT_CATALOG_NAME = "development"
              $BUILD_VERSION = "-dev.${{ github.run_number }}"
          } else {
              $ENVIRONMENT_CATALOG_NAME = "feature-branch/${{ github.ref_name }}"
              $BUILD_VERSION = ".${{ github.run_number }}"
          }
          echo "GITTAG=$($APP_VERSION)$($BUILD_VERSION)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $GITTAG = "$($APP_VERSION)$($BUILD_VERSION)"
          $NEXUS_USERNAME = "$env:NEXUS_USERNAME"
          $NEXUS_PASSWORD = ConvertTo-SecureString "$env:NEXUS_PASSWORD" -AsPlainText -Force  
          $AUTH = New-Object System.Management.Automation.PSCredential ($NEXUS_USERNAME, $NEXUS_PASSWORD)  
          Invoke-WebRequest -Uri https://nexus.mudita.com/repository/mudita-center/releases/$ENVIRONMENT_CATALOG_NAME/$($APP_VERSION)$($BUILD_VERSION)/Mudita-Center.exe -InFile ./packages/app/release/Mudita-Center.exe -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri https://nexus.mudita.com/repository/mudita-center/releases/$ENVIRONMENT_CATALOG_NAME/$($APP_VERSION)$($BUILD_VERSION)/Mudita-Center.exe.blockmap -InFile ./packages/app/release/Mudita-Center.exe.blockmap -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri https://nexus.mudita.com/repository/mudita-center/releases/$ENVIRONMENT_CATALOG_NAME/$($APP_VERSION)$($BUILD_VERSION)/latest.yml -InFile ./packages/app/release/latest.yml -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri https://nexus.mudita.com/repository/mudita-center/releases/$ENVIRONMENT_CATALOG_NAME/$($APP_VERSION)$($BUILD_VERSION)/builder-debug.yml -InFile ./packages/app/release/builder-debug.yml -Method Put -Credential $AUTH
          C:\"Program Files"\Git\cmd\git.exe clone https://${{ secrets.MC_GITHUB_ACCESS_TOKEN }}@github.com/mudita/mudita-center-internal-releases.git
          cd mudita-center-internal-releases
          C:\"Program Files"\Git\cmd\git.exe tag "$GITTAG"
          C:\"Program Files"\Git\cmd\git.exe push origin "$GITTAG"
      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./packages/app/release/Mudita-Center.exe
            ./packages/app/release/Mudita-Center.exe.blockmap
            ./packages/app/release/latest.yml
            ./packages/app/release/builder-debug.yml
          tag_name: ${{ env.GITTAG }}
          name: Mudita Center v${{ env.GITTAG }}
          repository: mudita/mudita-center-internal-releases
          token: ${{ secrets.MC_GITHUB_ACCESS_TOKEN }}
          draft: true
      - name: Push artifacts to GitHub
        id: upload_assets
        uses: actions/upload-artifact@v2
        with:
          name: release-assets
          path: |
            ./packages/app/release/Mudita-Center.exe
            ./packages/app/release/Mudita-Center.exe.blockmap
            ./packages/app/release/latest.yml
            ./packages/app/release/builder-debug.yml