name: Build & deploy to development

on:
  push:
    branches:
      - develop
      - CP-*
      - nexus-*
jobs:
  build:
    runs-on: Windows
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3
      - name: Setup Env
        env:
          PHRASE_API_KEY: ${{ secrets.PHRASE_API_KEY }}
          PHRASE_API_URL: ${{ secrets.PHRASE_API_URL }}
          PHRASE_API_KEY_DEV: ${{ secrets.PHRASE_API_KEY_DEV }}
          MUDITA_CENTER_SERVER_URL: ${{ secrets.MUDITA_CENTER_SERVER_URL }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
          RELEASES_REPOSITORY_NAME: ${{ secrets.RELEASES_REPOSITORY_NAME }}
          PRERELEASES_ENABLED: ${{ secrets.PRERELEASES_ENABLED }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.MC_GITHUB_ACCESS_TOKEN }}
          LOGIN_MICROSOFT_ONLINE_CLIENT_ID: ${{ secrets.LOGIN_MICROSOFT_ONLINE_CLIENT_ID }}
          FONTS_DIRECTORY_URL: ${{ secrets.FONTS_DIRECTORY_URL }}
          FRESHDESK_API_URL: ${{ secrets.FRESHDESK_API_URL }}
          FRESHDESK_API_TOKEN: ${{ secrets.FRESHDESK_API_TOKEN }}
          ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
          ANALYTICS_API_URL: ${{ secrets.ANALYTICS_API_URL }}
          ANALYTICS_API_SITE_ID: ${{ secrets.ANALYTICS_API_SITE_ID }}
          FEATURE_TOGGLE_ENVIRONMENT: ${{ secrets.FEATURE_TOGGLE_ENVIRONMENT }}
          STATIC_CONFIGURATION_FILE_PATH: ${{ secrets.STATIC_CONFIGURATION_FILE_PATH }}
          DEV_REDUX_LOGGER_ENABLED: ${{ secrets.DEV_REDUX_LOGGER_ENABLED }}
          DEV_DEVICE_LOGGER_ENABLED: ${{ secrets.DEV_DEVICE_LOGGER_ENABLED }}
          FEATURE_TOGGLE_RELEASE_ENVIRONMENT: ${{ secrets.FEATURE_TOGGLE_RELEASE_ENVIRONMENT }}
          MUDITA_CENTER_PRERELEASE_ENABLED: ${{ secrets.MUDITA_CENTER_PRERELEASE_ENABLED }}
        shell: cmd
        run: |
          SET > .env
          jq -r -j .version packages/app/package.json > packages/app/version
      - name: Setup depedencies
        run: npm run setup
      - name: Copy electron-builder environment file
        run: |
          copy C:\actions-runner\envs\electron-builder.env packages/app/electron-builder.env
      - name: Build App
        run: |
          $env:NODE_OPTIONS="--max-old-space-size=4096"
          cd packages/app/
          npm run dist:prod:all
      - name: Push artifacts to nexus registry
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          $APP_VERSION = Get-Content -Path "packages/app/version"
          if ($env:GITHUB_REF -eq "refs/heads/develop" -or $env:GITHUB_REF -eq "refs/heads/nexus-runner") {
              $ENVIRONMENT_CATALOG_NAME = "development"
              $BUILD_VERSION = "-dev.${$env:GITHUB_RUN_NUMBER}"
          } else {
              $env:ENVIRONMENT_CATALOG_NAME = "feature-branch/$($env:GITHUB_REF)"
              $env:BUILD_VERSION = ".$($env:GITHUB_RUN_NUMBER)"
          }
          $GITTAG = "$($env:APP_VERSION)$($env:BUILD_VERSION)"
          $NEXUS_URL = "https://nexus.mudita.com/repository/mudita-center/releases/$($ENVIRONMENT_CATALOG_NAME)/$($APP_VERSION)"
          $NEXUS_USERNAME = "$env:NEXUS_USERNAME"
          $NEXUS_PASSWORD = ConvertTo-SecureString "$env:NEXUS_PASSWORD" -AsPlainText -Force  
          $AUTH = New-Object System.Management.Automation.PSCredential ($NEXUS_USERNAME, $NEXUS_PASSWORD)  
          Invoke-WebRequest -Uri ${$NEXUS_URL}/Mudita-Center.exe -InFile ./packages/app/release/Mudita-Center.exe -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri ${$NEXUS_URL}/Mudita-Center.zip -InFile ./packages/app/release/Mudita-Center.zip -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri ${$NEXUS_URL}/Mudita-Center.zip.blockmap -InFile ./packages/app/release/Mudita-Center.zip.blockmap -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri ${$NEXUS_URL}/Mudita-Center.exe.blockmap -InFile ./packages/app/release/Mudita-Center.exe.blockmap -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri ${$NEXUS_URL}/latest.yml -InFile ./packages/app/release/Mudita-Center.latest.yml -Method Put -Credential $AUTH
          Invoke-WebRequest -Uri ${$NEXUS_URL}/builder-debug.yml -InFile ./packages/app/release/builder-debug.yml -Method Put -Credential $AUTH